### ISSUE TITLE
Any way to require alignment in serialized output?

### ISSUE THREAD

**Issue by vlovich** [zakarumych/alkahest#19]
I'm storing a alkahest::Bytes within a formula, but I want to make sure that when serialized they have a certain alignment within the output stream. Is there any way to accomplish this? I would think it's something along the lines of using a `&'de [u64]`, but I don't know what the equivalent is of `alkahest::Bytes` for representing `[u64]` in a formula (+ `[u64]` would be a bit weird because I don't actually have a requirement that the data length is a multiple of 8, just that some data I'm accessing within it is aligned such).

**Comment by zakarumych** [comment]
I guess that you want zero-copy deserialization of bytes and receive `&'de [u8]` which must be aligned.
Currently there's no way to specify alignment for serialized data. For this reason there's no way to zero-copy deserilaize other integer slices because it would require alignment.

Adding alignment requirement would also make `deserialize` to require largest alignment for the input data.

If you need to pass `&[u8]` to a function that requires aligned pointer you have few options.
1. Copy data to the new array allocated with alignment.
2. Get aligned sub-slice. Only if your use-case permits it.
3. Remove alignment requirement.

Option 1 would be fastest to do as workaround until alkahest allows specifying alignment.

**Comment by vlovich** [comment]
Kk. I assumed as much. I went with a different approach & just store that data outside of alkahest.
